
# This file is automatically generated, you probably don't want to edit this

contTablesPairedOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "contTablesPairedOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            rows = NULL,
            cols = NULL,
            counts = NULL,
            chiSq = TRUE,
            chiSqCorr = FALSE,
            exactBinom = FALSE,
            symmetry = FALSE,
            margHom = FALSE,
            oddsRatio = TRUE,
            oddsExact = FALSE,
            diffProp = TRUE,
            ci = TRUE,
            ciWidth = 95,
            pcRow = FALSE,
            pcCol = FALSE,
            pcMarg = FALSE,
            agreement = FALSE,
            kappa = FALSE,
            kappaWeighted = FALSE, ...) {

            super$initialize(
                package="conttablespaired2xK",
                name="contTablesPaired",
                requiresData=TRUE,
                ...)

            private$..rows <- jmvcore::OptionVariable$new(
                "rows",
                rows,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..cols <- jmvcore::OptionVariable$new(
                "cols",
                cols,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..counts <- jmvcore::OptionVariable$new(
                "counts",
                counts,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"),
                default=NULL)
            private$..chiSq <- jmvcore::OptionBool$new(
                "chiSq",
                chiSq,
                default=TRUE)
            private$..chiSqCorr <- jmvcore::OptionBool$new(
                "chiSqCorr",
                chiSqCorr,
                default=FALSE)
            private$..exactBinom <- jmvcore::OptionBool$new(
                "exactBinom",
                exactBinom,
                default=FALSE)
            private$..symmetry <- jmvcore::OptionBool$new(
                "symmetry",
                symmetry,
                default=FALSE)
            private$..margHom <- jmvcore::OptionBool$new(
                "margHom",
                margHom,
                default=FALSE)
            private$..oddsRatio <- jmvcore::OptionBool$new(
                "oddsRatio",
                oddsRatio,
                default=TRUE)
            private$..oddsExact <- jmvcore::OptionBool$new(
                "oddsExact",
                oddsExact,
                default=FALSE)
            private$..diffProp <- jmvcore::OptionBool$new(
                "diffProp",
                diffProp,
                default=TRUE)
            private$..ci <- jmvcore::OptionBool$new(
                "ci",
                ci,
                default=TRUE)
            private$..ciWidth <- jmvcore::OptionNumber$new(
                "ciWidth",
                ciWidth,
                min=50,
                max=99.9,
                default=95)
            private$..pcRow <- jmvcore::OptionBool$new(
                "pcRow",
                pcRow,
                default=FALSE)
            private$..pcCol <- jmvcore::OptionBool$new(
                "pcCol",
                pcCol,
                default=FALSE)
            private$..pcMarg <- jmvcore::OptionBool$new(
                "pcMarg",
                pcMarg,
                default=FALSE)
            private$..agreement <- jmvcore::OptionBool$new(
                "agreement",
                agreement,
                default=FALSE)
            private$..kappa <- jmvcore::OptionBool$new(
                "kappa",
                kappa,
                default=FALSE)
            private$..kappaWeighted <- jmvcore::OptionBool$new(
                "kappaWeighted",
                kappaWeighted,
                default=FALSE)

            self$.addOption(private$..rows)
            self$.addOption(private$..cols)
            self$.addOption(private$..counts)
            self$.addOption(private$..chiSq)
            self$.addOption(private$..chiSqCorr)
            self$.addOption(private$..exactBinom)
            self$.addOption(private$..symmetry)
            self$.addOption(private$..margHom)
            self$.addOption(private$..oddsRatio)
            self$.addOption(private$..oddsExact)
            self$.addOption(private$..diffProp)
            self$.addOption(private$..ci)
            self$.addOption(private$..ciWidth)
            self$.addOption(private$..pcRow)
            self$.addOption(private$..pcCol)
            self$.addOption(private$..pcMarg)
            self$.addOption(private$..agreement)
            self$.addOption(private$..kappa)
            self$.addOption(private$..kappaWeighted)
        }),
    active = list(
        rows = function() private$..rows$value,
        cols = function() private$..cols$value,
        counts = function() private$..counts$value,
        chiSq = function() private$..chiSq$value,
        chiSqCorr = function() private$..chiSqCorr$value,
        exactBinom = function() private$..exactBinom$value,
        symmetry = function() private$..symmetry$value,
        margHom = function() private$..margHom$value,
        oddsRatio = function() private$..oddsRatio$value,
        oddsExact = function() private$..oddsExact$value,
        diffProp = function() private$..diffProp$value,
        ci = function() private$..ci$value,
        ciWidth = function() private$..ciWidth$value,
        pcRow = function() private$..pcRow$value,
        pcCol = function() private$..pcCol$value,
        pcMarg = function() private$..pcMarg$value,
        agreement = function() private$..agreement$value,
        kappa = function() private$..kappa$value,
        kappaWeighted = function() private$..kappaWeighted$value),
    private = list(
        ..rows = NA,
        ..cols = NA,
        ..counts = NA,
        ..chiSq = NA,
        ..chiSqCorr = NA,
        ..exactBinom = NA,
        ..symmetry = NA,
        ..margHom = NA,
        ..oddsRatio = NA,
        ..oddsExact = NA,
        ..diffProp = NA,
        ..ci = NA,
        ..ciWidth = NA,
        ..pcRow = NA,
        ..pcCol = NA,
        ..pcMarg = NA,
        ..agreement = NA,
        ..kappa = NA,
        ..kappaWeighted = NA)
)

contTablesPairedResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "contTablesPairedResults",
    inherit = jmvcore::Group,
    active = list(
        freqs = function() private$.items[["freqs"]],
        test = function() private$.items[["test"]],
        odds = function() private$.items[["odds"]],
        agree = function() private$.items[["agree"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Paired Samples Contingency Tables")
            self$add(jmvcore::Table$new(
                options=options,
                name="freqs",
                title="Contingency Tables",
                columns=list(),
                clearWith=list(
                    "rows",
                    "cols",
                    "counts")))
            self$add(jmvcore::Table$new(
                options=options,
                name="test",
                title="Paired Tests",
                clearWith=list(
                    "rows",
                    "cols",
                    "counts"),
                columns=list(
                    list(
                        `name`="name[mcn]", 
                        `title`="", 
                        `type`="text", 
                        `content`="McNemar \u03C7\u00B2", 
                        `visible`="(chiSq)"),
                    list(
                        `name`="value[mcn]", 
                        `title`="Value", 
                        `visible`="(chiSq)"),
                    list(
                        `name`="df[mcn]", 
                        `title`="df", 
                        `type`="integer", 
                        `visible`="(chiSq)"),
                    list(
                        `name`="p[mcn]", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto,pvalue", 
                        `visible`="(chiSq)"),
                    list(
                        `name`="name[cor]", 
                        `title`="", 
                        `type`="text", 
                        `content`="McNemar \u03C7\u00B2 continuity correction", 
                        `visible`="(chiSqCorr)"),
                    list(
                        `name`="value[cor]", 
                        `title`="Value", 
                        `visible`="(chiSqCorr)"),
                    list(
                        `name`="df[cor]", 
                        `title`="df", 
                        `type`="integer", 
                        `visible`="(chiSqCorr)"),
                    list(
                        `name`="p[cor]", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto,pvalue", 
                        `visible`="(chiSqCorr)"),
                    list(
                        `name`="name[bin]", 
                        `title`="", 
                        `type`="text", 
                        `content`="Exact test (binomial)", 
                        `visible`="(exactBinom)"),
                    list(
                        `name`="value[bin]", 
                        `title`="Value", 
                        `visible`="(exactBinom)"),
                    list(
                        `name`="df[bin]", 
                        `title`="df", 
                        `content`="", 
                        `visible`="(exactBinom)"),
                    list(
                        `name`="p[bin]", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto,pvalue", 
                        `visible`="(exactBinom)"),
                    list(
                        `name`="name[bow]", 
                        `title`="", 
                        `type`="text", 
                        `content`="Bowker's test of symmetry", 
                        `visible`="(symmetry)", 
                        `refs`="bowker1948"),
                    list(
                        `name`="value[bow]", 
                        `title`="Value", 
                        `visible`="(symmetry)"),
                    list(
                        `name`="df[bow]", 
                        `title`="df", 
                        `type`="integer", 
                        `visible`="(symmetry)"),
                    list(
                        `name`="p[bow]", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto,pvalue", 
                        `visible`="(symmetry)"),
                    list(
                        `name`="name[sm]", 
                        `title`="", 
                        `type`="text", 
                        `content`="Stuart-Maxwell test of marginal homogeneity", 
                        `visible`="(margHom)", 
                        `refs`="stuart1955"),
                    list(
                        `name`="value[sm]", 
                        `title`="Value", 
                        `visible`="(margHom)"),
                    list(
                        `name`="df[sm]", 
                        `title`="df", 
                        `type`="integer", 
                        `visible`="(margHom)"),
                    list(
                        `name`="p[sm]", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto,pvalue", 
                        `visible`="(margHom)"),
                    list(
                        `name`="name[n]", 
                        `title`="", 
                        `type`="text", 
                        `content`="N"),
                    list(
                        `name`="value[n]", 
                        `title`="Value"),
                    list(
                        `name`="df[n]", 
                        `title`="df", 
                        `content`=""),
                    list(
                        `name`="p[n]", 
                        `title`="p", 
                        `content`=""))))
            self$add(jmvcore::Table$new(
                options=options,
                name="odds",
                title="Comparative Measures",
                visible="(oddsRatio || oddsExact || diffProp)",
                clearWith=list(
                    "rows",
                    "cols",
                    "counts",
                    "ciWidth"),
                columns=list(
                    list(
                        `name`="t[dp]", 
                        `title`="", 
                        `type`="text", 
                        `content`="Difference in proportions", 
                        `visible`="(diffProp)"),
                    list(
                        `name`="v[dp]", 
                        `title`="Value", 
                        `visible`="(diffProp)"),
                    list(
                        `name`="cil[dp]", 
                        `title`="Lower", 
                        `superTitle`="Confidence Intervals", 
                        `visible`="(diffProp && ci)"),
                    list(
                        `name`="ciu[dp]", 
                        `title`="Upper", 
                        `superTitle`="Confidence Intervals", 
                        `visible`="(diffProp && ci)"),
                    list(
                        `name`="t[o]", 
                        `title`="", 
                        `type`="text", 
                        `content`="Odds ratio", 
                        `visible`="(oddsRatio)"),
                    list(
                        `name`="v[o]", 
                        `title`="Value", 
                        `visible`="(oddsRatio)"),
                    list(
                        `name`="cil[o]", 
                        `title`="Lower", 
                        `superTitle`="Confidence Intervals", 
                        `visible`="(oddsRatio && ci)"),
                    list(
                        `name`="ciu[o]", 
                        `title`="Upper", 
                        `superTitle`="Confidence Intervals", 
                        `visible`="(oddsRatio && ci)"),
                    list(
                        `name`="t[oe]", 
                        `title`="", 
                        `type`="text", 
                        `content`="Exact odds ratio", 
                        `visible`="(oddsExact)", 
                        `refs`="exact2x2"),
                    list(
                        `name`="v[oe]", 
                        `title`="Value", 
                        `visible`="(oddsExact)"),
                    list(
                        `name`="cil[oe]", 
                        `title`="Lower", 
                        `superTitle`="Confidence Intervals", 
                        `visible`="(oddsExact && ci)"),
                    list(
                        `name`="ciu[oe]", 
                        `title`="Upper", 
                        `superTitle`="Confidence Intervals", 
                        `visible`="(oddsExact && ci)"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="agree",
                title="Agreement",
                visible="(agreement || kappa || kappaWeighted)",
                clearWith=list(
                    "rows",
                    "cols",
                    "counts",
                    "ciWidth"),
                columns=list(
                    list(
                        `name`="t[obs]", 
                        `title`="", 
                        `type`="text", 
                        `content`="Observed agreement", 
                        `visible`="(agreement)"),
                    list(
                        `name`="v[obs]", 
                        `title`="Value", 
                        `visible`="(agreement)"),
                    list(
                        `name`="cil[obs]", 
                        `title`="Lower", 
                        `superTitle`="Confidence Intervals", 
                        `visible`="(agreement && ci)"),
                    list(
                        `name`="ciu[obs]", 
                        `title`="Upper", 
                        `superTitle`="Confidence Intervals", 
                        `visible`="(agreement && ci)"),
                    list(
                        `name`="t[kap]", 
                        `title`="", 
                        `type`="text", 
                        `content`="Cohen's kappa", 
                        `visible`="(kappa)", 
                        `refs`=list(
                            "vcd",
                            "mchugh2012")),
                    list(
                        `name`="v[kap]", 
                        `title`="Value", 
                        `visible`="(kappa)"),
                    list(
                        `name`="cil[kap]", 
                        `title`="Lower", 
                        `superTitle`="Confidence Intervals", 
                        `visible`="(kappa && ci)"),
                    list(
                        `name`="ciu[kap]", 
                        `title`="Upper", 
                        `superTitle`="Confidence Intervals", 
                        `visible`="(kappa && ci)"),
                    list(
                        `name`="t[wkap]", 
                        `title`="", 
                        `type`="text", 
                        `content`="Weighted kappa", 
                        `visible`="(kappaWeighted)", 
                        `refs`=list(
                            "vcd",
                            "cohen1968")),
                    list(
                        `name`="v[wkap]", 
                        `title`="Value", 
                        `visible`="(kappaWeighted)"),
                    list(
                        `name`="cil[wkap]", 
                        `title`="Lower", 
                        `superTitle`="Confidence Intervals", 
                        `visible`="(kappaWeighted && ci)"),
                    list(
                        `name`="ciu[wkap]", 
                        `title`="Upper", 
                        `superTitle`="Confidence Intervals", 
                        `visible`="(kappaWeighted && ci)"))))}))

contTablesPairedBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "contTablesPairedBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "conttablespaired2xK",
                name = "contTablesPaired",
                version = c(1,0,0),
                options = options,
                results = contTablesPairedResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = TRUE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Paired Samples Contingency Tables
#'
#' McNemar's test for paired binary data, extended with a paired odds ratio 
#' and difference in proportions (with confidence intervals), marginal 
#' percentages, agreement/kappa, and — for RxR tables — Bowker's test of 
#' symmetry and the Stuart-Maxwell test of marginal homogeneity.
#' 
#'
#' @examples
#' dat <- data.frame(
#'     `1st survey` = c('Approve', 'Approve', 'Disapprove', 'Disapprove'),
#'     `2nd survey` = c('Approve', 'Disapprove', 'Approve', 'Disapprove'),
#'     `Counts` = c(794, 150, 86, 570),
#'     check.names=FALSE)
#'
#' conttablespaired2xK::contTablesPaired(formula = Counts ~ `1st survey`:`2nd survey`, data = dat)
#'
#' #
#' #  PAIRED SAMPLES CONTINGENCY TABLES
#' #
#' #  Paired Tests
#' #  -------------------------------------------------------------
#' #                                        Value    df    p
#' #  -------------------------------------------------------------
#' #    McNemar X²                           17.4     1    < .001
#' #    McNemar X² continuity correction     16.8     1    < .001
#' #  -------------------------------------------------------------
#' #
#' #
#' #  Comparative Measures
#' #  -------------------------------------------------------------
#' #                                    Value    Lower    Upper
#' #  -------------------------------------------------------------
#' #    Odds ratio                       1.74     1.34     2.28
#' #    Difference in proportions        0.04     0.02     0.06
#' #  -------------------------------------------------------------
#' #
#'
#' # Alternatively, omit the left of the formula (`Counts`) from the
#' # formula if each row represents a single observation:
#'
#' conttablespaired2xK::contTablesPaired(formula = ~ `1st survey`:`2nd survey`, data = dat)
#'
#' @param data the data as a data frame
#' @param rows the variable to use as the rows in the contingency table (not
#'   necessary when providing a formula, see the examples)
#' @param cols the variable to use as the columns in the contingency table
#'   (not necessary when providing a formula, see the examples)
#' @param counts the variable to use as the counts in the contingency table
#'   (not necessary when providing a formula, see the examples)
#' @param chiSq \code{TRUE} (default) or \code{FALSE}, provide McNemar's X²
#'   (2x2 tables only)
#' @param chiSqCorr \code{TRUE} or \code{FALSE} (default), provide X² with
#'   continuity correction (2x2 tables only)
#' @param exactBinom \code{TRUE} or \code{FALSE} (default), provide McNemar's
#'   exact test based on the binomial distribution (2x2 tables only)
#' @param symmetry \code{TRUE} or \code{FALSE} (default), provide Bowker's
#'   test of symmetry (the RxR generalization of McNemar's X²; computed for any
#'   square table, i.e. rows and columns sharing the same categories -- for a
#'   2x2 table it is numerically identical to the uncorrected X²)
#' @param margHom \code{TRUE} or \code{FALSE} (default), provide the
#'   Stuart-Maxwell test of marginal homogeneity (the RxR generalization of the
#'   difference in proportions test; computed for any square table -- for a 2x2
#'   table it is numerically identical to the uncorrected McNemar X²)
#' @param oddsRatio \code{TRUE} (default) or \code{FALSE}, provide the paired
#'   odds ratio (b/c, Wald confidence interval; 2x2 tables only). Reference is
#'   the first category, for both rows and columns
#' @param oddsExact \code{TRUE} or \code{FALSE} (default), provide an exact
#'   conditional MLE odds ratio with an exact confidence interval (requires
#'   exact2x2 to be installed; 2x2 tables only)
#' @param diffProp \code{TRUE} (default) or \code{FALSE}, provide the
#'   difference between the two paired (marginal) proportions, with a Wald
#'   confidence interval (2x2 tables only). Reference is the first category, for
#'   both rows and columns
#' @param ci \code{TRUE} (default) or \code{FALSE}, provide confidence
#'   intervals for the comparative measures and for kappa
#' @param ciWidth a number between 50 and 99.9 (default: 95), width of the
#'   confidence intervals to provide
#' @param pcRow \code{TRUE} or \code{FALSE} (default), provide row percentages
#' @param pcCol \code{TRUE} or \code{FALSE} (default), provide column
#'   percentages
#' @param pcMarg \code{TRUE} or \code{FALSE} (default), provide marginal
#'   percentages (each row/column category's share of the grand total) on the
#'   Total row and Total column — the relevant percentages for a paired design,
#'   as opposed to the within-row/within-column percentages above
#' @param agreement \code{TRUE} or \code{FALSE} (default), provide the
#'   observed agreement (the diagonal share of the table, as a proportion)
#' @param kappa \code{TRUE} or \code{FALSE} (default), provide Cohen's kappa,
#'   with a confidence interval
#' @param kappaWeighted \code{TRUE} or \code{FALSE} (default), provide a
#'   weighted kappa using linear weights, with a confidence interval (tables
#'   with more than 2 categories only). Categories are assumed to be ordered
#' @param formula (optional) the formula to use, see the examples
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$freqs} \tab \tab \tab \tab \tab a table of frequencies and percentages \cr
#'   \code{results$test} \tab \tab \tab \tab \tab a table of test results \cr
#'   \code{results$odds} \tab \tab \tab \tab \tab a table of comparative measures (2x2 tables only) \cr
#'   \code{results$agree} \tab \tab \tab \tab \tab a table of agreement measures \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$freqs$asDF}
#'
#' \code{as.data.frame(results$freqs)}
#'
#' @export
contTablesPaired <- function(
    data,
    rows,
    cols,
    counts = NULL,
    chiSq = TRUE,
    chiSqCorr = FALSE,
    exactBinom = FALSE,
    symmetry = FALSE,
    margHom = FALSE,
    oddsRatio = TRUE,
    oddsExact = FALSE,
    diffProp = TRUE,
    ci = TRUE,
    ciWidth = 95,
    pcRow = FALSE,
    pcCol = FALSE,
    pcMarg = FALSE,
    agreement = FALSE,
    kappa = FALSE,
    kappaWeighted = FALSE,
    formula) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("contTablesPaired requires jmvcore to be installed (restart may be required)")

    if ( ! missing(formula)) {
        if (missing(counts))
            counts <- jmvcore::marshalFormula(
                formula=formula,
                data=`if`( ! missing(data), data, NULL),
                from="lhs",
                type="vars",
                subset="1")
        if (missing(rows))
            rows <- jmvcore::marshalFormula(
                formula=formula,
                data=`if`( ! missing(data), data, NULL),
                from="rhs",
                type="vars",
                subset="1")
        if (missing(cols))
            cols <- jmvcore::marshalFormula(
                formula=formula,
                data=`if`( ! missing(data), data, NULL),
                from="rhs",
                type="vars",
                subset="2")
    }

    if ( ! missing(rows)) rows <- jmvcore::resolveQuo(jmvcore::enquo(rows))
    if ( ! missing(cols)) cols <- jmvcore::resolveQuo(jmvcore::enquo(cols))
    if ( ! missing(counts)) counts <- jmvcore::resolveQuo(jmvcore::enquo(counts))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(rows), rows, NULL),
            `if`( ! missing(cols), cols, NULL),
            `if`( ! missing(counts), counts, NULL))

    for (v in rows) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in cols) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- contTablesPairedOptions$new(
        rows = rows,
        cols = cols,
        counts = counts,
        chiSq = chiSq,
        chiSqCorr = chiSqCorr,
        exactBinom = exactBinom,
        symmetry = symmetry,
        margHom = margHom,
        oddsRatio = oddsRatio,
        oddsExact = oddsExact,
        diffProp = diffProp,
        ci = ci,
        ciWidth = ciWidth,
        pcRow = pcRow,
        pcCol = pcCol,
        pcMarg = pcMarg,
        agreement = agreement,
        kappa = kappa,
        kappaWeighted = kappaWeighted)

    analysis <- contTablesPairedClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

